# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShuftiPro Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShuftiPro Demo
  pod 'NFCPassportReader',:tag => '1.1.7', git:'https://github.com/AndyQ/NFCPassportReader.git'
  pod 'GoogleMLKit/TextRecognition'

end
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if ['NFCPassportReader'].include? target.name
#      target.build_configurations.each do |config|
#          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      end
#    end
#  end
#end

