# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShuftiPro Non OCR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShuftiPro Non OCR
pod 'IQKeyboardManagerSwift'
end
