# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShuftiPro Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShuftiPro Demo
pod 'ShuftiPro', :tag => '3.4.5', :git => "https://github.com/shuftipro/iOS-binary-pod"


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Socket.IO-Client-Swift', 'Starscream' ,'lottie-ios'].include? target.name
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
