# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shufti Pro Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shufti Pro Demo
 # pod 'NFCPassportReader', git:'https://github.com/AndyQ/NFCPassportReader.git'
  # pod 'GoogleMLKit/TextRecognition'

end
